### ISSUE TITLE
dotnet 3.1 solution with more than 1 project fails to build using S2I 

### ISSUE THREAD

**Issue by boukisge** [redhat-developer/s2i-dotnetcore#350]
I am trying to build an image for a single solution multi-project .NET Core 3.1 web application with local dependencies using S2I
strategy for OpenShift V4.4

Build config fails due to error "Skipping Project"/opt/app-root/src/Web.Model/Web.Model.csproj" because it was not found

**bc.yml snippet**

```yaml
strategy
 sourceStrategy
   env:
       - name: "DOTNET_STARTUP_PROJECT"
         value: "Web/Web.csproj"
       - name: "DOTNET_ASSEMBLY_NAME"
         value: "Web.Model/Web.Model.csproj"
```

Directory Structure - 4 projects , single repo

```
- Web  (top-level solution)
- Web
- Dependencies
-   Projects
-     Web.Model
- Nuget.config
- Web.csproj
- Web.API  
-    Dependencies
-      Projects
-        Web.Model
-        Web.DataAccess
- Web.API.csproj
- Web.Model
-      Web.Model.csproj
- Web.DataAccess
-      Web.DataAccess.csproj
```

is there an example for a S2I script that builds dependencies automatically
Does this use case require a custom assembly ?
